"""Verifier for the skeleton task.

Two things are graded independently. The report has to match the approved bytes for the
shipped inputs, and the agent's own program has to reproduce those bytes when re-run
against inputs it has never seen. The second is what stops a hand-written report from
passing: the artifact alone is cheap to fake, re-deriving it on held-out data is not.

Replace the whole file for a real task, but keep the shape: golden bytes, a held-out
re-run, and a determinism check.
"""

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

import pytest

APP = Path("/app")
SRC = APP / "src" / "summarize.py"
REPORT = APP / "out" / "report.json"
DATA = APP / "data"
HOLDOUT = Path("/tests/holdout")

# Scratch space owned by the sandbox user; see tests/Dockerfile.
WORK_OUT = Path("/work/out")

SANDBOX_UID = 12000
DROP_PRIVILEGES = [
    "setpriv",
    "--no-new-privs",
    f"--reuid={SANDBOX_UID}",
    f"--regid={SANDBOX_UID}",
    "--clear-groups",
]

# SHA-256 of the report each input set must produce. Generated from solution/src.
EXPECTED_PRIMARY = "60fec4718722649de61a0a56094fa49cf19597bd942244b27c77cea81352ce57"
EXPECTED_HOLDOUT = {"h1": "a3cca7560ba22f8ec8e43ead53cee7566e713086e19c21ef42bd785bc7da77ba"}


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def run_agent_program(data_dir, out_path):
    """Runs the agent's own program, unprivileged, against a directory of our choosing."""
    return subprocess.run(
        DROP_PRIVILEGES
        + ["python3", str(SRC), "--data", str(data_dir), "--out", str(out_path)],
        capture_output=True,
        text=True,
        timeout=120,
    )


def test_report_exists():
    """The declared artifact was produced at the documented path."""
    assert REPORT.is_file(), f"{REPORT} was not created"


def test_report_is_valid_json():
    """The report parses and carries the documented top-level keys."""
    data = json.loads(REPORT.read_text())
    assert set(data) == {"files", "total_words"}, f"unexpected top-level keys: {sorted(data)}"


def test_report_matches_approved_bytes():
    """The report is byte-identical to the approved output for the shipped inputs."""
    actual = sha256(REPORT)
    assert actual == EXPECTED_PRIMARY, (
        f"report.json does not match the approved bytes\n"
        f"  expected sha256 {EXPECTED_PRIMARY}\n  actual   sha256 {actual}"
    )


@pytest.mark.parametrize("name", sorted(EXPECTED_HOLDOUT))
def test_holdout_reproduces_approved_bytes(name):
    """Re-running the agent's program on unseen inputs reproduces the approved bytes.

    This is the anti-cheat axis: it proves the report on disk was generated by the
    program rather than written by hand or pinned to the shipped fixtures.
    """
    out = WORK_OUT / f"{name}.json"
    result = run_agent_program(HOLDOUT / name, out)
    assert result.returncode == 0, f"program failed on held-out set {name}:\n{result.stderr}"

    actual = sha256(out)
    assert actual == EXPECTED_HOLDOUT[name], (
        f"held-out set {name} did not reproduce the approved bytes\n"
        f"  expected sha256 {EXPECTED_HOLDOUT[name]}\n  actual   sha256 {actual}"
    )


def test_ordering_and_file_type_filtering():
    """Entries are ordered by name, and only regular .txt files count.

    Built at test time rather than baked into the image, so the on-disk layout is
    controlled directly instead of depending on how Docker COPY happens to order a
    directory. Names are created out of alphabetical order, and the fixture includes a
    non-.txt file plus a directory whose name matches *.txt, to prove the program sorts
    rather than relying on filesystem iteration order, and to prove it never treats a
    directory as one of "the .txt files".
    """
    case_dir = WORK_OUT / "order-case"
    if case_dir.exists():
        shutil.rmtree(case_dir)
    case_dir.mkdir(parents=True)
    case_dir.chmod(0o755)

    files = {
        "zebra.txt": "z z z\n",
        "mango.txt": "m m\n",
        "apple.txt": "a\n",
    }
    for name, contents in files.items():
        path = case_dir / name
        path.write_text(contents)
        path.chmod(0o644)
    (case_dir / "notes.md").write_text("not a .txt file, must be ignored\n")
    (case_dir / "notes.md").chmod(0o644)
    (case_dir / "diary.txt").mkdir()
    (case_dir / "diary.txt").chmod(0o755)

    out = WORK_OUT / "order-case.json"
    result = run_agent_program(case_dir, out)
    assert result.returncode == 0, f"program failed on the ordering/filter fixture:\n{result.stderr}"

    data = json.loads(out.read_text())
    names = [entry["name"] for entry in data["files"]]
    assert names == ["apple.txt", "mango.txt", "zebra.txt"], (
        f"files must be ordered by name and exclude non-.txt entries and directories, got {names}"
    )
    expected_total = sum(len(contents.split()) for contents in files.values())
    assert data["total_words"] == expected_total, (
        f"total_words must be the sum of word counts, expected {expected_total}, got {data['total_words']}"
    )


def test_output_is_deterministic():
    """Two runs over the same inputs produce identical bytes."""
    first, second = WORK_OUT / "det-1.json", WORK_OUT / "det-2.json"
    for out in (first, second):
        assert run_agent_program(DATA, out).returncode == 0, "program failed on shipped inputs"
    assert sha256(first) == sha256(second), "program output is not deterministic"
